### PR TITLE
Update fr.md

### PR DESCRIPTION
**Pull request by GravenilvecTV**
+ Add Java formation link
+ Add Python formation link

### CODE REVIEW

**Comment by exybore** [comment]
I think these tutorials are great to learn development. 👍

**Comment by DevelopHeureShell** [comment]
I am not a Java or Python developer, but these videos seems to be good. I will learn Python with this tutorial.

**Comment by Kawacrepe** [comment]
Maybe you should close this PR ?

**Comment by rault-a** [comment]
I think that this your videos does not target the same audience as learndev do (your video are more like popularization while learndev target more people that are already familiar with development and try to dive deep into a language)

**Comment by exybore** [comment]
And it’s a big _cheh_ for graven

**Pull request closed without merging**
